# Site settings
title: 端点星
description: 端点星
favicon: /assets/img/avatar.JPG
baseurl:
url: https://zolro.github.io
rss_url:

# Build settings

highlight: true
#highlighter: rouge


markdown: kramdown
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style
